sylius_resource:
    resources:
        app.user:
            driver: doctrine/orm
            object_manager: default
            templates: AppBundle:User
            classes:
                model: AppBundle\Entity\User
                controller: Sylius\Bundle\ResourceBundle\Controller\ResourceController
                repository: AppBundle\Repository\UserRepository
